### PR TITLE
Overall cleanup 2021

### PR DESCRIPTION
**Pull request by freghar**
Please go through the changes commit-by-commit (the "Commits" tab above) -- the commit messages give you context and I've tried **hard** to logically split the changes so they're easy to review.

Note that some of these changes might be controversial, so please let me know (add an inline comment or PR comment here) if you see something that shouldn't be changed without a Brainstorming thread. Also please let me know if you see something in error (ie. enforcing something that shouldn't be enforced).

I realize it's quite a few commits, but the settings IMO needed a bit of a face-lift.

Finally, I have not touched LAMBS settings - this is possibly something to fix later as some that seems like they should be at least mission-enforced (`lambs_danger_radioDisabled`) are left for players to customize.

Thanks!

### CODE REVIEW

**Comment by freghar** [comment]
I've removed ACE map gesture and pointing range increases; after some testing, ACE measures meters differently than vanilla and the current values are actually fine.

**Review by JamesTheClarke — APPROVED** [review]
https://github.com/CntoDev/cba-settings-lock/pull/15/commits/3724845c51937a6c32a7c31f288afce49b75c926: Approved - this change makes sense, very likely an oversight due to an ACE update of the past because this used to be the default.

https://github.com/CntoDev/cba-settings-lock/pull/15/commits/0db40bdb641f7a5c51478370ed128bd426f20370: Approved - no major gameplay impact and does make things a bit more interesting.

https://github.com/CntoDev/cba-settings-lock/pull/15/commits/f13b52752a2338c4a129fcd63cf9af21c3683780: Approved - no major gameplay changes and only comes into play when MM manually changes it for individual missions.

**Review by JamesTheClarke — APPROVED** [review]
.

**Review by JamesTheClarke — APPROVED** [review]
.

**Review by JamesTheClarke — CHANGES_REQUESTED** [review]
https://github.com/CntoDev/cba-settings-lock/pull/15/commits/3724845c51937a6c32a7c31f288afce49b75c926: Approved - probably an oversight during a past ACE3 update.

https://github.com/CntoDev/cba-settings-lock/pull/15/commits/0db40bdb641f7a5c51478370ed128bd426f20370: Approved - no major gameplay change and could make things a bit more interesting.

https://github.com/CntoDev/cba-settings-lock/pull/15/commits/f13b52752a2338c4a129fcd63cf9af21c3683780: Approved - no major gameplay change and only comes into play when MM activates it for individual missions.

https://github.com/CntoDev/cba-settings-lock/pull/15/commits/f0365f2e39b47e3e5781aa6f31201286fac79b7a: Approved - no major gameplay changes and gives people more minor customisation options.

https://github.com/CntoDev/cba-settings-lock/pull/15/commits/0e112b651d3d5e81a1e73e89b87481bef2a1d1e8: This one I would challenge. Originally these settings were enforced to give MMs the option to craft survival missions for special events. Disabling the enforcement doesn't really gain us much from what I can see but keeping them leaves the option for MMs to involve survival rations without clients being able to fiddle with the settings themselves.

https://github.com/CntoDev/cba-settings-lock/pull/15/commits/284d0d8173ee5810dd260b8cf3e96fe9b3523020: Approved - good points, they were not considered when the settings were chosen in the past.

https://github.com/CntoDev/cba-settings-lock/pull/15/commits/e3ddc1f300ab6e4cdc4728beeb2e9a204f89a6a5: Not approved - these settings are currently still under the discussion in the Staff Forums and that's where further changes should be discussed before going live as it's one of our main gameplay tools in every op. https://www.carpenoctem.co/forums/m/26081621/viewthread/33389709-dui-squad-radar-setup . One further change has already been approved but not yet implemented: we'll allow clients to disable the directional radar hud as per Hateboarders Brainstorming thread.

https://github.com/CntoDev/cba-settings-lock/pull/15/commits/25a30d320ae9fd7cbc93907a7dd6289a06266ec8: Approved - those are all fine, I was considering shortly that ace explosive timers could be useful for MMs to manipulate but it hasn't happened in the past at all so I'm good with solidifying this setting server-side for now.

**Comment by freghar** [comment]
> 0e112b6: This one I would challenge. Originally these settings were enforced to give MMs ...

OK, removed, makes sense.

> e3ddc1f: Not approved - these settings are currently still under the discussion in the Staff Forums ...

Removed any changes (incl. mission enforcement --> server enforcement from the last commit) related to DUI.

**Review by JamesTheClarke — APPROVED** [review]

**Pull request merged**
