### PR TITLE
v2.2.3 Update

### LINKED ISSUE #33: LAMBS Settings
@freghar mentioned on Discord that LAMBS settings should be taken a look at. Just opening an issue to keep track of this and maybe implement a change for the next cba file update.

Reference: https://discord.com/channels/154907081256730624/281495773894410240/826046297894420520

### LINKED ISSUE #34: ACRE2 Post-Mix Volume Setting
This issue report is inspired by something @freghar posted in Brainstorming: https://www.carpenoctem.co/forums/page/4/m/26081621/viewthread/33453813-jsrs/post/139541123#p139541123

In early 2015 we did a lot of testing regarding ACRE2 voice volume settings and determined that the following settings deliver the best results for most players over distance:

```
force force acre_sys_core_premixGlobalVolume = 1;
force force acre_sys_core_postmixGlobalVolume = 3;
```

For a long while, these settings were set to `force force` meaning enforced server-side. However, at some point, we removed the `force force`, ~~most likely due to complaints that this volume mix is too loud for some members depending on their individual audio setup. From that point onwards players were able to adjust the baseline settings on their own.~~
CORRECTION: this change was very likely a direct result of the ACRE2 mod update described below and thus was not intentional, found a forum thread from December 2019 that still shows `force force` enabled: https://www.carpenoctem.co/forums/m/26081621/viewthread/32974694-acre2-update-testing-report/post/138260285#p138260285

An ACRE2 mod update some time in 2020 reset the CBA settings to:

```
acre_sys_core_premixGlobalVolume = 1;
acre_sys_core_postmixGlobalVolume = 1;
```

most likely because at the time I didn't do the full cba comparison procedure as described in the [wiki here](https://github.com/CntoDev/cba-settings-lock/wiki/Updating-settings-on-modset-update), thus some default mod settings snuck back in.

My proposal is to set the values back to:

```
acre_sys_core_premixGlobalVolume = 1;
acre_sys_core_postmixGlobalVolume = 3;
```

to address the volume issues people describe in louder mods (JSRS, Star Wars etc.) but to NOT reintroduce `force force`, that way clients can still adjust the settings to their personal setups. However, the default volume baseline would be more appropriate with post-mix 3.0 as long as JSRS is in use.

**Note: this change would not affect any enforcement settings. It merely raises the baseline of the general voice volume. Players can still lower or raise that baseline on their own accord.**

### PR DESCRIPTION
**Pull request by JamesTheClarke**
- changed all newer LAMBS settings from `client-side` to `force`, ensures no conflicts between clients and mission and gives Mission Maker the options to tweak or disable any LAMBS setting - in line with existing settings of LAMBS which were all set to `force`: fixes #33
- changed `acre_sys_core_postmixGlobalVolume = 1;` to `acre_sys_core_postmixGlobalVolume = 3;` - no changes to enforcements (still client side), should address voice audio issues for most players with JSRS, all clients can still lower or raise their pre-mix/post-mix settings: fixes #34

Due to an increase of the baseline setting for voice volume a positive review of all SSgts is required before deployment on the server!

### CODE REVIEW

**Comment by Shiny-CNTO** [comment]
Before I approve this I would like to see a comparison to what exactly the difference in audio is. Do you have an example or a short video where we can hear the difference? I can't get from the text what exactly this difference would be except that we change it from 1 to 3.  It would also be good to know which menu option can change this setting. Is this under ACRE ?

**Comment by JamesTheClarke** [comment]
The issue report #34 goes into more detail @Shiny-CNTO. As stated there for the majority of the community this used to be our standard-setting anyways. We determined it way back when we tested it with Bullhorn and our discussions with the ACRE2 dev team.

To reiterate, this won't change any enforcement, users can still lower or raise both pre and post mix volumes as they see fit. It would just be an easy fix for most players complaining about the voice volume issues when using JSRS.

**Comment by Shiny-CNTO** [comment]
I read it but I don't understand what changing 1 to 3 means.
Does it mean the ACRE volume will be 200% louder? Are we getting members that will not fiddle with their settings be ear raped after this change? 
Would like a little more clarity on what changes for everyone as that is not explained. All I keep reading is that this used to be 3 and we changed it at one point. But what exactly does that mean.

**Comment by JamesTheClarke** [comment]
It's definitely not 200% louder, from what I can tell it's a gradient audio curve. If you need comparison footage watch any YT video posted by CNTO before January 2020 and then compare it to what you play now. I've found this forum thread that shows we still used `force force acre_sys_core_postmixGlobalVolume = 3;` in December 2019: https://www.carpenoctem.co/forums/m/26081621/viewthread/32974694-acre2-update-testing-report/post/138260285#p138260285

Loudness complaints were not mass spread, though I can definitely remember some being there. My personal acre2 settings currently hover between 1.5 and 2 depending on the mission but I do have very sensitive audio setups where 3 would be a tad too loud, though by no means painful or unplayable.

**Comment by Shiny-CNTO** [comment]
Ok as an alternative isn't it then better to propose to change it to 2 and remove the force so users can move it to 3 if they want it louder? I am just worried that we will have multiple people asking where they can change this and that it's too loud.

**Comment by JamesTheClarke** [comment]
I'm ok with `acre_sys_core_postmixGlobalVolume = 2;` as an initial baseline. Personally, I'm not having any issues currently because I already increased my post-mix values. I just want to provide some kind of basic support for members who haven't realised that they can adjust the voice volume atm.

I'm also ok with not changing anything in ACRE2 post-mix volume and revert this change to 1.0 until a relevant Staff Forum discussion is held. Either way is fine by me, I just don't want to delay the LAMBS fixes too long so MM's have more control over what LAMBS settings are active in their missions.

**Comment by Shiny-CNTO** [comment]
Agreed. I think moving it to 2 because we are not entirely clear on what will change might be a bit better. If we receive any feedback then we know at least what this can be and it shouldn't be too loud for anyone.
Will leave my review in a few.

**Review by Shiny-CNTO — CHANGES_REQUESTED** [review]
As said in the comments. Since we are not entirely clear on how much louder the volume can be on a end user perspective it might be better to change the postmixglobalvolume to 2 instead of 3. Once that is changed I will approve the changes.

**Comment by Shadisica** [comment]
I'm fine with going to volume 2 and seeing from there, yeah.

**Review by Shadisica — DISMISSED** [review]

**Comment by freghar** [comment]
Has anybody tested whether
```
acre_sys_core_postmixGlobalVolume = 2;
```
in `cba_settings.sqf` on the server actually does anything to the client?

**Comment by JamesTheClarke** [comment]
> Has anybody tested whether
> 
> ```
> acre_sys_core_postmixGlobalVolume = 2;
> ```
> 
> in `cba_settings.sqf` on the server actually does anything to the client?

It does not change the client setting if the client already has a local profile including said setting. However it will help in two cases:

1.) new players who don't yet have a local profile that includes an acre setting
2.) current players who want to quickly load the "recommended" CNTO default client settings without having to set them all individually by loading them from the server profile.

But you are 100% correct, if you have a profile already set to x value this change will not override it unless you load the profile. I should have been more specific about this in earlier conversations but I assumed this was understood.

**Review by Shadisica — APPROVED** [review]

**Comment by freghar** [comment]
> It does not change the client setting if the client already has a local profile including said setting. However it will help in two cases:
> 
> 1.) new players (Recruits) who don't yet have a local profile that includes an acre setting

I still think this is false, however the second point is fair enough.

**Comment by JamesTheClarke** [comment]
> > It does not change the client setting if the client already has a local profile including said setting. However it will help in two cases:
> > 1.) new players (Recruits) who don't yet have a local profile that includes an acre setting
> 
> I still think this is false, however the second point is fair enough.

I've tested this in the past after deleting my local profile I would join the server and have settings preset depending on what the server set as default, but ONLY if I didn't have said setting saved somewhere in my local profile before. However, I do admit I haven't repeated this since and it's been two years so my memory may be spotty in this regard.

Could be worth repeating. :)

**Comment by freghar** [comment]
There seems to be something wrong with this PR - it seems to merge master in some weird way where it revers at least some changes already done on master, ie. LAMBS update and a3aa.

**Review by Shadisica — DISMISSED** [review]

**Comment by JamesTheClarke** [comment]
> There seems to be something wrong with this PR - it seems to merge master in some weird way where it revers at least some changes already done on master, ie. LAMBS update and a3aa.

Yeah I just noticed that too. There was a "conflict" showing up earlier after the change requested. I tried to resolve the conflict but must have messed up somewhere. I'll recommit.

**Comment by JamesTheClarke** [comment]
@freghar should be fixed now right? if yes please drop a short review.

**Review by freghar — APPROVED** [review]
looks good

**Review by milivojm — APPROVED** [review]

**Review by Shadisica — APPROVED** [review]

**Review by Shiny-CNTO — APPROVED** [review]
Lookin good chief

**Comment by JamesTheClarke** [comment]
Still getting the conflict error I never encountered before on Github and don't really know how to resolve it atm. However, the changes were reviewed by four people and are very straight forward, thus I've deployed them on the server for tomorrows operation. Will solve the Github issue in the interim.

**Pull request merged**
