### PR TITLE
V2.2.4 Update

### LINKED ISSUE #36: Force-Enable AI Scope Removal by Default
As per our Staff Forum discussion: https://www.carpenoctem.co/forums/m/26081621/viewthread/33517739-remove-ai-1x-scopes-from-that-are-snipers-by-default/post/last#last

The new AI scope removal cba setting created by @Seb105 will be enabled as `force` - that means Mission Makers will still be able to manually disable said feature if they choose to.

### LINKED ISSUE #37: Make ACEX Headless optional
Change
```
force force acex_headless_enabled = true;
```
to
```
force acex_headless_enabled = true;
```
so that we can replace it with A3AA locality transfer on a test mission.

### LINKED ISSUE #38: Aircraft Turbulence defaults are out of date.
```
force force HELICOPTER_TURBULENCE_MAX_TURBULENCE = 15;
force force HELICOPTER_TURBULENCE_MIN_TURBULENCE = 3;
force force PLANE_TURBULENCE_MAX_TURBULENCE = 15;
force force PLANE_TURBULENCE_MIN_TURBULENCE = 3;
```
The defaults are now 9 and 2 respectively.

Also, it's really dumb that these are all force force'd. You should at least let MAX_TURBULENCE and WEATHER_EFFECT be customised for mission makers.

### LINKED ISSUE #39: LAMBS Radio Sharing Setting
As per Monthly Meeting April 2021 we will change the LAMBS radio setting to

`force lambs_main_radioDisabled = true`

which disables radio sharing by default but allows for Mission Makers to enable it if they so choose.

https://www.carpenoctem.co/forums/page/2/m/26081621/viewthread/33510774-lambs-sucks-some-workarounds/post/139603830#p139603830

### LINKED ISSUE #40: Check CBA Settings for the latest Repo Updates
https://www.carpenoctem.co/forums/m/26081621/viewthread/16086660-a3sync-repository-status/post/139593311#p139593311

https://www.carpenoctem.co/forums/page/24/m/26081621/viewthread/16086660-a3sync-repository-status/post/139610501#p139610501

The latest Main Repo Updates have introduced a few existing class name changes and potentially new settings.

Check:

- [x] @3den_enhanced (v6.0.02)
- [x] @acre2 (v2.9.0.1042)
- [x] @dui_squad_radar (v1.9.1)
- [x] @lambs_danger (v2.5.1)
- [x] @zen (v1.10.0)
- [x] @grad_trenches (v1.6.8 )
- [x] @enhanced_movement_rw (v0.6.6)

### LINKED ISSUE #42: ACE Medical Changes
https://www.carpenoctem.co/forums/page/6/m/26081621/viewthread/33452198-what-do-you-like-or-hate-about-current-medical-system/post/139608992#p139608992

According to the April Monthly Meeting decisions following changes have to be made to the CBA settings:

- `force force ace_medical_bleedingCoefficient = 0.6;` to `force force ace_medical_bleedingCoefficient = 0.8;`
- `force force ace_medical_treatment_treatmentTimeTourniquet = 7;` to `force force ace_medical_treatment_treatmentTimeTourniquet = 4;`

### PR DESCRIPTION
**Pull request by JamesTheClarke**
// ACEX

- changed `acex_headless_enabled = true;` from `force force` to `force` to enable locality transfer test missions - fixes #37

// ACE3 Medical

- changed `force force ace_medical_bleedingCoefficient = 0.6;` to `force force ace_medical_bleedingCoefficient = 0.8;` - fixes #42 

- changed `force force ace_medical_treatment_treatmentTimeTourniquet = 7;` to `force force ace_medical_treatment_treatmentTimeTourniquet = 4;` - fixes #42 
 
// CNTO Additions

- changed `force cnto_scope_remover_enable = false;` to `force cnto_scope_remover_enable = true;` - fixes #36

// Enhanced Movement Rework

- set `emr_main_dropViewElevation = -0.7;` and `emr_main_enableWalkableSurface = true;` to `force force` in line with the rest of Enhanced Movement Rework settings - fixes #40

// GRAD Trenches

- set `grad_trenches_functions_bigEnvelopeRemovalTime = -1;`, `grad_trenches_functions_giantEnvelopeRemovalTime = -1;`, `grad_trenches_functions_LongEnvelopeRemovalTime = -1;`, `grad_trenches_functions_shortEnvelopeRemovalTime = -1;`, `grad_trenches_functions_smallEnvelopeRemovalTime = -1;` and `grad_trenches_functions_vehicleEnvelopeRemovalTime = -1;` to `force force` in line with the rest of GRAD settings - fixes #40

// LAMBS

- set `force lambs_main_radioDisabled = false;` to `force lambs_main_radioDisabled = true;` - fixes #39

// Turbulence Mods

- corrected default turbulence mod values from max. 15 and min. 3 to max. 9 and min. 2 - fixes #38

-------------------------------------------------------------------------

Min. 2 positive reviews needed before merger into Master and deployment on the server!

### CODE REVIEW

**Comment by freghar** [comment]
Looks good, but it seems #38 also mentioned:
> Also, it's really dumb that these are all force force'd. You should at least let MAX_TURBULENCE and WEATHER_EFFECT be customised for mission makers.

Was this left as-is (`force force`) intentionally?

**Review by freghar — DISMISSED** [review]

**Comment by JamesTheClarke** [comment]
> Looks good, but it seems #38 also mentioned:
> 
> > Also, it's really dumb that these are all force force'd. You should at least let MAX_TURBULENCE and WEATHER_EFFECT be customised for mission makers.
> 
> Was this left as-is (`force force`) intentionally?
> 
> edit: Just saw the forum post, ok.

Yeah, the `force force` settings were chosen after a lengthy debate when the mod was orginally introduced. I wasn't going to revert that decision after an impromptu mentioning of the brainstorming thread created less than a day before the April Monthly Meeting. We'll be discussing the `force force` setting specifically again in the May Monthly Meeting and afterwards either revert it to `force` or keep as is.

**Comment by JamesTheClarke** [comment]
Sry @freghar just realised I didn't include the necessary medical changes in my last commit. hot fixed it. please review again.

**Review by freghar — APPROVED** [review]
Looks good (again).

**Review by Shadisica — APPROVED** [review]
Lookin' good!

**Review by Shiny-CNTO — APPROVED** [review]
Ready to merge! Looks great

**Comment by JamesTheClarke** [comment]
Deployed on the private server.

**Pull request merged**
